apiVersion: v1
kind: Service
metadata:
  labels:
    app: revflixp2storing
    name: revflixp2storing
spec:
  ports:
  - name: revflixp2storing
    port: 80
    targetPort: storing-port
  selector:
    app: revflixp2storing
  type: LoadBalancer