apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: revflixp2service
  name: revflixp2service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: revflixp2service
  template:
    metadata:
      labels:
        app: revflixp2service
    spec:
      containers:
      - image: rennerpa93/revflixp2service
        name: revflixp2service
        ports:
          - containerPort: 80
            name: revflixp2service-port