apiVersion: v1
kind: Service
metadata:
  labels:
    app: revflixp2service
    name: revflixp2service
spec:
  ports:
  - name: revflixp2service
    port: 80
    targetPort: revflixp2service-port
  selector:
    app: revflixp2service
  type: LoadBalancer