apiVersion: v1
kind: Service
metadata:
  labels:
    app: revflixp2client
  name: revflixp2client
spec:
  ports:
  - name: revflixp2client
    port: 80
    targetPort: client-port
  selector:
    app: revflixp2client
  type: LoadBalancer